### ISSUE TITLE
app/assets/stylesheets/application.bootstrap.scss does not appear to exist

### ISSUE THREAD

**Issue by sig-krasnick** [driftingruby/template#1]
I'm getting the error message that bootstrap.scss does not appear to exist.  
It appears that bootstrap is missing from the Gemfile, so there isn't a bootstrap.scss file.  The only css files that are created are 
create  app/assets/stylesheets/application.css
and 
create    app/assets/stylesheets/drifting_ruby.css

The after_bundler event is trying to modify the non-existent.scss file with the @import drifting_ruby line of code and then does not continue.

Please let me know if there is an additional flag that I'm supposed to use to include bootstrap.  

I wasn't using a .railsrc file and creating the application using the -m flag. I tried it again with the --css bootstrap and that seems to work fine.  so maybe it's just an issue for the README

**Comment by kobaltz** [comment]
Did you launch the rails application with `bin/dev` instead of `bin/rails server`?

**Comment by sig-krasnick** [comment]
The error comes up when creating a new rails application using the template if you leave off the --css=bootstrap processor flag. It happens after the new project has been bundled. 

I would think the error would also happen if --css=tailwind or any other css app generator is used other than bootstrap.
This appears to be where the error is happening.  https://github.com/driftingruby/template/blob/79f2741aa73275c398518b4e34d0e44dbd5749ea/template.rb#L46

**Comment by kobaltz** [comment]
Ah yes. That would be expected. I do note in the README, that I have a `~/.railsrc` file which has `--css=bootstrap` as a flag that is automatically passed in whenever I create a new rails app.

**Comment by alexventuraio** [comment]
So, it is a must to pass the `--css=bootstrap` or `--css=tailwind` flag to make it work, right?

**Comment by kobaltz** [comment]
`--css=bootstrap` is the correct flag. I don't use tailwind on the episode content, so there would be lots of little fixes to do as well as the template erroring out at line 46. This repository is used whenever I create a new Rails app for the www.driftingruby.com screencasts.

**Comment by alexventuraio** [comment]
Oh, I see, so I will work on some adjustments to use it with TailwindCSS, thanks @kobaltz!
